on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - uses: actions/checkout@v4
    - name: Install pip packages
      working-directory: docs
      run: |
        pip install pip --upgrade
        pip install -r requirements.txt --upgrade

    - name: Build doc
      working-directory: docs
      run: |
        export GIT_LFS_TO_LINKS="true"
        export GIT_ORG_REPOSITORY="${{ github.repository }}"
        [ "${{ github.event_name }}" = "pull_request" ] \
          && export GIT_BRANCH="${{ github.event.pull_request.head.ref }}" \
          || export GIT_BRANCH="${{ github.ref_name }}"

        [[ "${{ runner.debug }}" != "1" ]] && j_="-jauto"

        make html SPHINXOPTS="$j_"

    - name: Store the generated doc
      uses: actions/upload-artifact@v4
      with:
        name: html
        path: docs/_build/html

  deploy:
    runs-on: ubuntu-latest
    needs: [build-doc]
    permissions:
      contents: write
    if: >
      github.ref == 'refs/heads/main' ||
      github.event_name == 'pull_request' ||
      github.ref_type == 'tag'

    steps:
    - uses: analogdevicesinc/doctools/gh-pages-deploy@action
      with:
        new_tag: ${{ github.ref_type == 'tag' }}
        tag: ${{ github.ref_name }}
        name: html

